name: dassert
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.22.0
  characters: ^1.3.0

dev_dependencies:
  lints: ^2.0.1
